# Getting Police Data

In [1]:
# Set Up
import pandas as pd
import numpy as np

In [3]:
la = pd.read_json('https://data.lacounty.gov/resource/d6xt-ws3m.json')
la.head()

,:@computed_region_x8wy_s94z,approx_latitude,approx_longitude,city,deputy_race,geo_location,handling_unit_id,handling_unit_name,incident_date,incident_location,...,of_involved_deputies,of_suspects,of_suspects_deceased,of_suspects_wounded,reporting_district,state,suspect_race,weapon_involved_category,weapon_involved_category_desc,zip
0,24349,33.895891,-118.224837,COMPTON,"HISPANIC,HISPANIC,HISPANIC","{'latitude': '33.895891', 'longitude': '-118.2...",COM,COMPTON STN,2014-12-31T17:00:00.000,100 WEST COMPTON BLVD,...,3,1,1,0,2814.0,CA,HISPANIC,A-1,"FIREARM: Suspect armed, Firearm recovered",90220.0
1,24349,33.888420,-118.237096,COMPTON,"HISPANIC,HISPANIC","{'latitude': '33.88842', 'longitude': '-118.23...",COM,COMPTON STN,2019-03-31T22:47:00.000,600 W. ALONDRA BLVD,...,2,2,0,2,2835.0,CA,"HISPANIC,HISPANIC",A-1,"FIREARM: Suspect armed, Firearm recovered",90220.0
2,22350,33.970271,-118.260616,LOS ANGELES,HISPANIC,"{'latitude': '33.970271', 'longitude': '-118.2...",CEN,CENTURY STN,2011-04-05T20:59:00.000,800 E. 76TH PLACE,...,1,2,0,2,2172.0,CA,"HISPANIC,HISPANIC",A-1,"FIREARM: Suspect armed, Firearm recovered",90001.0
3,23441,34.014597,-118.180012,LOS ANGELES,"ASIAN-PACIFIC-ISL,HISPANIC","{'latitude': '34.014597', 'longitude': '-118.1...",ELA,EAST LA STN,2011-08-20T20:30:00.000,1400 SOUTH DOWNEY ROAD,...,2,1,1,0,278.0,CA,HISPANIC,A-1,"FIREARM: Suspect armed, Firearm recovered",90063.0
4,24349,33.886113,-118.225869,COMPTON,WHITE,"{'latitude': '33.886113', 'longitude': '-118.2...",OSS,OPERATION SAFE STREETS BUREAU,2010-11-11T17:35:00.000,300 CLAUDE STREET,...,1,1,0,0,2836.0,CA,BLACK,A-1,"FIREARM: Suspect armed, Firearm recovered",90220.0

# LA Arrest Data
https://data.lacity.org/A-Safe-City/Arrest-Data-from-2010-to-Present/yru6-6re4

In [29]:
from sodapy import Socrata

In [40]:
client = Socrata(domain = "data.lacity.org",
                 app_token = '202kdbcr8rw88adxrerfomyrr',
                 username= "truong.winson@berkeley.edu",
                 password = '201bwgkbul3plcyebtjgmniziye6fbtpwle3dtt2oarugo6g5u')

raw = client.get("yru6-6re4")

# Convert to pandas DataFrame
raw_df = pd.DataFrame.from_records(results, limit = 500000)

HTTPError: 403 Client Error: Forbidden.
	Authentication failed: Too many login attempts for that login. Account temporarily disabled.